##################################################
# DO Community Playbooks: LEMP on Ubuntu 18.04
##################################################
---
- hosts: webservers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/default.yml

  tasks:

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    # Install PHP
    - name: install PHP repository
      apt_repository:
        repo: ppa:ondrej/php

    - name: Update apt-get repo and cache
      apt: update_cache=yes

    - name: install PHP packages
      apt:
        pkg:
          - git
          - mcrypt
          - nginx
          - php7.3
          - php7.3-fpm
          - php7.3-cli
          - php7.3-curl
          - php7.3-intl
          - php7.3-json
        state: present
        autoclean: yes
    
    # Nginx Configuration    
    - name: Start php-fpm
      service:
        name: "php{{phpfpm_version}}-fpm"
        state: "started"  

    # Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

  # Handlers      
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted